### ISSUE TITLE
Documentation !

### ISSUE THREAD

**Issue by mpoiriert** [ebussola/facebook-ads#1]
Any documentation would be great. I could probably manage from reading the unit test but since I don't even know how the facebook ads api works it will be really time consuming... No need to have a full extend documentation, having something is better than nothing ;)

**Comment by shina** [comment]
Hello! Yes, I have to do it.

Actually this is part of a bunch of libs I'm refactoring from a legacy code. So I'm running with the code, but I'll focus on documentation soon.

Thanks for the tip.

**Comment by mpoiriert** [comment]
Is it worth for me to try to understand it like it's implemented right now or you'll do major change in the code ? Also I will probably do a symfony 2 integration of your library so with both "project" (your library stand alone and my symfony integration) it could give a good visibility to yours !

When are you planning to document ? I will plan my development in consequence...

**Comment by shina** [comment]
I'm not planning to do major changes in the code. I appreciate if you make a Bundle of this project =)

About the documentation, I want to make it soon, but I can't tell you a date, sorry.
I'll leave this thread opened to remember me to do it and when i do it and close the thread, you will know.

**Comment by mpoiriert** [comment]
Is it possible that you implemented only the read part of the api ? If i want to create a campaign/ad you didn't implement this part ?

**Comment by shina** [comment]
Yes, It's only read yet.
